//@version=4
study("Calculated colors", "", true)
color i_c_ma = input(color.olive, "MA")
color i_c_close = input(color.blue, "Close")
float ma = sma(close, 20)
float maHeight = percentrank(ma, 100)
float transparency = min(80, 100 - maHeight)
// This plot uses a calculated color.
plot(ma, "MA1", color.new(i_c_ma, transparency), 2)
// This plot does not use a calculated color.
plot(close, "Close", i_c_close)