import { PREFIX, removePrefix, extractFunctionName } from "../../utils/v2/common";
import { Series } from "./Series";
import { __SIGNATURES__, __CONTEXT_AWARE__ } from "./stdlib";

// Define Trade Types
export interface Trade {
    id: string;
    entryTime: number;
    entryPrice: number;
    exitTime: number;
    exitPrice: number;
    qty: number;
    pnl: number;
    direction: "long" | "short";
}

export interface Position {
    size: number;      // + for Long, - for Short
    avgPrice: number;
}

export interface PlotData {
    value: number;
    title: string;
    color?: string;
    linewidth?: number;
    style?: any;
    type: 'line' | 'shape' | 'char' | 'bar';
}

export interface FillData {
    plotId1: string; // The ID of the first line
    plotId2: string; // The ID of the second line
    color: string;
    title: string;
}

export class Context {
    // 1. Internal Execution State (Private)
    protected callStack: string[] = [];
    private states: Map<string, any> = new Map();

    // 2. Series Registry
    // Key = Variable Name (e.g. "opsv2_close", "opsv2_myVar")
    private vars: Map<string, Series> = new Map();

    // 3. Market Data (Public)
    public time: number = 0;
    public open: number = 0;
    public high: number = 0;
    public low: number = 0;
    public close: number = 0;
    public volume: number = 0;

    // 4. Engine State (Public)
    public currentBarIndex: number = 0; 
    public plots: Map<string, (PlotData | null)[]> = new Map(); 
    public fills: Map<string, (FillData | null)[]> = new Map();

    // 5. Strategy State (Public)
    public position: Position = { size: 0, avgPrice: 0 };
    public cash: number = 100000; 
    public trades: Trade[] = [];
    public orders: any[] = [];
    
    // 6. Built-in Constants
    public opsv2_na: number = NaN;

    constructor() {}

    // --- BUILT-IN GETTERS (Crucial Fix) ---
    // These map the Transpiled Names (opsv2_*) to the Internal State
    public get opsv2_open(): number { return this.open; }
    public get opsv2_high(): number { return this.high; }
    public get opsv2_low(): number { return this.low; }
    public get opsv2_close(): number { return this.close; }
    public get opsv2_volume(): number { return this.volume; }
    public get opsv2_time(): number { return this.time; }
    public get opsv2_bar_index(): number { return this.currentBarIndex; }

    public reset() {
        this.callStack = [];
        // Note: 'vars' persists across bars.
    }

    /**
     * SMART CALL EXECUTION
     * Handles:
     * 1. Context Injection
     * 2. Keyword Argument Resolution (kwargs)
     */
    public call(id: string, fn: Function, ...args: any[]) {
        const identity = id; 
        this.callStack.push(identity);
        
        try {
            // 1. Extract Function Name from ID (e.g. "ta.sma_L10_C4" -> "ta.sma")
            // We strip the Location Tag (_Lxx_Cxx)
            const fname = removePrefix(extractFunctionName(id)); 

            // 2. Handle Keyword Arguments
            // Check if the last argument is a Kwargs Object (generated by Transpiler)
            const lastArg = args[args.length - 1];
            const hasKwargs = lastArg && typeof lastArg === 'object' && !Array.isArray(lastArg) 
                              && !(lastArg instanceof Series) && lastArg.constructor === Object;

            let finalArgs = args;

            if (hasKwargs) {
                // Remove the kwargs object from the list
                const positionalArgs = args.slice(0, -1);
                const kwargs = lastArg;

                // Lookup Signature
                const params = __SIGNATURES__[fname];
                
                if (params) {
                    finalArgs = [...positionalArgs];
                    
                    // Map keys (e.g. "color") to their index
                    for (const [_key, val] of Object.entries(kwargs)) {
                        const key = PREFIX + _key; // Add prefix to avoid collisions
                        const index = params.indexOf(key);
                        if (index !== -1) {
                            // Pad array if needed
                            while (finalArgs.length < index) {
                                finalArgs.push(undefined);
                            }
                            finalArgs[index] = val;
                        }
                    }
                } else {
                    // Fallback: If no signature found (User function?), keep args as is
                    // or define behavior for user-defined kwargs (not supported in v2)
                    finalArgs = positionalArgs; 
                }
            }

            // 3. Inject Context (if required)
            if (__CONTEXT_AWARE__.includes(fname)) {
                return fn(this, ...finalArgs);
            } else {
                return fn(...finalArgs);
            }

        } finally {
            this.callStack.pop();
        }
    }

    public getPersistentState<T>(initFn: () => T): T {
        const key = this.callStack.length > 0 ? this.callStack.join("/") : "global";
        if (!this.states.has(key)) {
            this.states.set(key, initFn());
        }
        return this.states.get(key);
    }

    // --- Series Management ---

    /**
     * FACTORY: Creates or Updates a Series Object.
     */
    public new_var(name: string, val: any): Series {
        let series = this.vars.get(name);
        
        if (!series) {
            series = new Series(this, name);
            this.vars.set(name, series);
        }

        // FIX: Check if 'val' is a Series Object (Duck Typing)
        // If so, grab its current value (.value property or valueOf() result)
        // We assume your Series class has a .value property for the current bar.
        // If not, we rely on standard JS conversion or we need to add a check.
        
        let numericVal: number;
        
        if (val && typeof val.get === 'function' && typeof val.valueOf === 'function') {
             // It's a Series! Get the primitive value.
             numericVal = val.valueOf();
        } else {
             // It's a number (or NaN)
             numericVal = Number(val);
        }

        return series.update(numericVal);
    }

    /**
     * FACTORY (Tuple): Handles assignments like [a, b] = func()
     */
    public new_vars(names: string[], values: any): Series[] {
        const vals = Array.isArray(values) ? values : [values];

        return names.map((name, index) => {
            const val = (index < vals.length) ? vals[index] : NaN;
            // Unwrap potential Series object to raw number
            const numVal = Number(val); 
            return this.new_var(name, isNaN(numVal) ? NaN : numVal);
        });
    }

    /**
     * Universal History Accessor (Called by transpiled code: [])
     */
    public get(target: any, offset: number, id: string): number {
        // Case A: Series Object (Duck Typing check for speed)
        if (target && typeof target.get === 'function') {
            return target.get(offset);
        }

        // Case B: Raw Number (Expression) -> Fallback to Local History Lookup
        return this.getSeries(id, offset);
    }

    /**
     * Internal helper for fallback lookups
     */
    public getSeries(name: string, offset: number): number {
        const series = this.vars.get(name);
        return series ? series.get(offset) : NaN;
    }

    public setBar(time: number, open: number, high: number, low: number, close: number, volume: number) {
        // 1. Update Public Props
        this.time = time;
        this.open = open;
        this.high = high;
        this.low = low;
        this.close = close;
        this.volume = volume;

        // 2. Update Series Objects
        this.new_var("opsv2_time", time);
        this.new_var("opsv2_open", open);
        this.new_var("opsv2_high", high);
        this.new_var("opsv2_low", low);
        this.new_var("opsv2_close", close);
        this.new_var("opsv2_volume", volume);
    }

    // --- Plotting ---

    public registerPlot(
        value: number, 
        title: string = "Plot", 
        options: { 
            color?: string, 
            linewidth?: number, 
            style?: any,
            type?: 'line' | 'shape' | 'char' | 'bar'
        } = {}
    ) {
        // 1. Get the Unique Call ID (Storage Key)
        // This ensures that "plot(close)" and "plot(open)" don't overwrite each other 
        // just because they both default to title="Plot".
        const id = this.callStack.length > 0 
            ? this.callStack[this.callStack.length - 1] 
            : title;

        // 2. Use ID to retrieve the series
        let series = this.plots.get(id);

        if (!series) {
            series = [];
            this.plots.set(id, series); // Store by ID
            
            // Backfill history if this plot appears conditionally later in the script
            while (series.length < this.currentBarIndex) {
                series.push(null);
            }
        }

        const data: PlotData = {
            value: Number(value), // 3. Ensure Primitive Number
            title: title,         // 4. Store Display Title (can be duplicate)
            color: options.color,
            linewidth: options.linewidth,
            style: options.style,
            type: options.type || 'line'
        };

        if (series.length > this.currentBarIndex) {
            series[this.currentBarIndex] = data;
        } else {
            series.push(data);
        }
    }

    public registerFill(id1: string, id2: string, options: { color?: string, title?: string } = {}) {
        const title = options.title || `Fill_${id1}_${id2}`;
        
        let series = this.fills.get(title);
        if (!series) {
            series = [];
            this.fills.set(title, series);
            while (series.length < this.currentBarIndex) {
                series.push(null);
            }
        }

        const data: FillData = {
            plotId1: id1,
            plotId2: id2,
            color: options.color || "#00000000",
            title: title
        };

        if (series.length > this.currentBarIndex) {
            series[this.currentBarIndex] = data;
        } else {
            series.push(data);
        }
    }

    public finalizeBar() {
        this.plots.forEach((series) => {
            if (series.length <= this.currentBarIndex) {
                series.push(null);
            }
        });
        this.fills.forEach((series) => {
            if (series.length <= this.currentBarIndex) {
                series.push(null);
            }
        });
        this.currentBarIndex++;
    }
}
