//@version=4
study("Conditional colors", "", true)
int i_legs    = input(5, "Pivot Legs", minval = 1)
color i_c_pHi = input(color.olive, "High pivots")
color i_c_pLo = input(color.orange, "Low pivots")
// Intialize the pivot level variables.
var float pHi = na
var float pLo = na
// When a new pivot is detected, save its value.
pHi := nz(pivothigh(i_legs, i_legs), pHi)
pLo := nz(pivotlow( i_legs, i_legs), pLo)
// When a new pivot is detected, do not plot a color.
plot(pHi, "High", change(pHi) ? na : i_c_pHi, 2, plot.style_line)
plot(pLo, "Low",  change(pLo) ? na : i_c_pLo, 2, plot.style_line)