export const core = {
    "na": (x: any): boolean => x === null || x === undefined || (typeof x === 'number' && isNaN(x)),
    "nz": (x: any, y?: any): any => (x === null || x === undefined || (typeof x === 'number' && isNaN(x))) ? (y ?? 0) : x,
    "iff": (cond: boolean, t: any, f: any): any => cond ? t : f,
  
    "abs": Math.abs,
    "acos": Math.acos,
    "asin": Math.asin,
    "atan": Math.atan,
    "ceil": Math.ceil,
    "cos": Math.cos,
    "exp": Math.exp,
    "floor": Math.floor,
    "log": Math.log,
    "log10": Math.log10,
    "max": Math.max,
    "min": Math.min,
    "pow": Math.pow,
    "round": Math.round,
    "sign": Math.sign,
    "sin": Math.sin,
    "sqrt": Math.sqrt,
    "tan": Math.tan,
    "avg": (...args: number[]): number => args.reduce((a, b) => a + b, 0) / args.length,
};
