import { Context } from "../context";

export const __IS_NAMESPACE__ = true;

/**
 * Returns true if the current bar is a historical bar.
 * @getter
 */
export function ishistory(ctx: Context): boolean {
    return ctx.is_history;
}

/**
 * Returns true if the current bar is a real-time bar.
 * @getter
 */
export function isrealtime(ctx: Context): boolean {
    return ctx.is_realtime;
}

/**
 * Returns true if this is the first execution on the current bar.
 * @getter
 */
export function isnew(ctx: Context): boolean {
    return ctx.is_new;
}

/**
 * Returns true if this is the last historically available bar.
 * @getter
 */
export function islast(ctx: Context): boolean {
    return ctx.is_last;
}

/**
 * Returns true on the script's FIRST bar.
 *
 * Derived from the bar counter rather than stored as a flag, so it cannot fall
 * out of step with `bar_index` — they are the same fact.
 *
 * Present in Pine since v1 and absent here until v5 needed it: every harness
 * generated by scripts/common/make-log-harness.ts writes its CSV header under
 * `if barstate.isfirst`, and a missing member of an EXISTING namespace reads as
 * `undefined` rather than erroring (the namespace-root check in the emitter
 * deliberately does not assert registry completeness), so the header was
 * silently never emitted.
 *
 * @getter
 */
export function isfirst(ctx: Context): boolean {
    return ctx.currentBarIndex === 0;
}
