/**
 * Pine Script drawing objects — `line`, `label`, `box`, `table`.
 *
 * `line` and `label` arrived June 2019, `box` and `table` in May 2021, all
 * under v4 (see the v4 release notes). The registry split in ./index.ts keeps
 * the whole set out of the v1–v3 view, so a v3 script naming `label.new` is
 * refused there rather than by a check here.
 *
 * ── WHAT THIS DOES AND DOES NOT DO ──────────────────────────────────────────
 *
 * A drawing is recorded on the Context with an id and its properties, and the
 * setters mutate that record. It is NOT rendered, and it does not participate
 * in `plots` — a drawing is an object with a lifetime, not a per-bar value, and
 * TradingView's exported chart data does not contain drawings either. So
 * nothing here can affect the golden-parity numbers.
 *
 * The point is that a script which draws RUNS. A large fraction of published v4
 * indicators label their signals, and before this they died on the first
 * `label.new` — which said nothing about whether their arithmetic was right.
 *
 * Getters return what was set. `line.get_price(id, x)` is the one that computes
 * rather than recalls, because it is the only one a script reads back into its
 * own maths.
 */

import { Context } from "../context";
import { val } from "../../../utils/v2/common";

const v = (x: any): any => val(x);
const n = (x: any): number => Number(val(x));

/**
 * ⚠ EVERY MEMBER BELOW IS WRITTEN OUT LITERALLY, AND MUST STAY THAT WAY.
 *
 * The registry is generated by scripts/generate-metadata.ts, which walks these
 * object literals with ts-morph and records each PropertyAssignment it finds.
 * It does not evaluate the file — so a member added by a spread
 *
 *     ...setters("line", ["x1", "y1", …])
 *
 * exists at run time and is invisible to the generator. The first draft of this
 * file did exactly that: `line.get_price` worked, because it was a literal
 * property, while `line.get_y2` came back "The provided reference is not a
 * function" — the sandbox had no entry to call.
 *
 * So the repetition is load-bearing. These two helpers hold the shared BODY;
 * the property names have to be spelled out.
 */

/** Assigns a property on a drawing, coercing through `val`. */
function setProp(ctx: Context, id: any, fn: string, prop: string, value: any): void {
    ctx.getDrawing(id, fn).props[prop] = v(value);
}

/** Assigns a NUMERIC property — coordinates and widths. */
function setNum(ctx: Context, id: any, fn: string, prop: string, value: any): void {
    ctx.getDrawing(id, fn).props[prop] = n(value);
}

/** Recalls a property. */
function getProp(ctx: Context, id: any, fn: string, prop: string): any {
    return ctx.getDrawing(id, fn).props[prop];
}

// ── line ────────────────────────────────────────────────────────────────────

export const line = {
    new: (
        ctx: Context, x1: any, y1: any, x2: any, y2: any,
        xloc: any = "bar_index", extend: any = "none",
        color: any = "#2196F3", style: any = "solid", width: any = 1,
    ) => ctx.newDrawing("line", {
        x1: n(x1), y1: n(y1), x2: n(x2), y2: n(y2),
        xloc: v(xloc), extend: v(extend), color: v(color), style: v(style), width: n(width),
    }),

    set_x1: (ctx: Context, id: any, x: any) => setNum(ctx, id, "line.set_x1", "x1", x),
    set_y1: (ctx: Context, id: any, y: any) => setNum(ctx, id, "line.set_y1", "y1", y),
    set_x2: (ctx: Context, id: any, x: any) => setNum(ctx, id, "line.set_x2", "x2", x),
    set_y2: (ctx: Context, id: any, y: any) => setNum(ctx, id, "line.set_y2", "y2", y),
    set_width: (ctx: Context, id: any, width: any) => setNum(ctx, id, "line.set_width", "width", width),
    set_xloc: (ctx: Context, id: any, xloc: any) => setProp(ctx, id, "line.set_xloc", "xloc", xloc),
    set_extend: (ctx: Context, id: any, extend: any) => setProp(ctx, id, "line.set_extend", "extend", extend),
    set_color: (ctx: Context, id: any, color: any) => setProp(ctx, id, "line.set_color", "color", color),
    set_style: (ctx: Context, id: any, style: any) => setProp(ctx, id, "line.set_style", "style", style),

    get_x1: (ctx: Context, id: any) => getProp(ctx, id, "line.get_x1", "x1"),
    get_y1: (ctx: Context, id: any) => getProp(ctx, id, "line.get_y1", "y1"),
    get_x2: (ctx: Context, id: any) => getProp(ctx, id, "line.get_x2", "x2"),
    get_y2: (ctx: Context, id: any) => getProp(ctx, id, "line.get_y2", "y2"),

    /** Both endpoints at once — one call in Pine, so one call here. */
    set_xy1: (ctx: Context, id: any, x: any, y: any) => {
        const p = ctx.getDrawing(id, "line.set_xy1").props;
        p.x1 = n(x); p.y1 = n(y);
    },
    set_xy2: (ctx: Context, id: any, x: any, y: any) => {
        const p = ctx.getDrawing(id, "line.set_xy2").props;
        p.x2 = n(x); p.y2 = n(y);
    },

    /**
     * The price the line takes at bar `x`, by linear interpolation through its
     * two endpoints — extrapolated beyond them, which is what makes the
     * trendline-projection idiom work.
     *
     * Vertical lines have no single price, so they are `na` rather than ±∞.
     */
    get_price: (ctx: Context, id: any, x: any) => {
        const p = ctx.getDrawing(id, "line.get_price").props;
        if (p.x2 === p.x1) return NaN;
        return p.y1 + (p.y2 - p.y1) * ((n(x) - p.x1) / (p.x2 - p.x1));
    },

    delete: (ctx: Context, id: any) => {
        ctx.drawings.delete(String(v(id)));
    },
    copy: (ctx: Context, id: any) =>
        ctx.newDrawing("line", { ...ctx.getDrawing(id, "line.copy").props }),

    // Style constants.
    style_solid: "solid",
    style_dotted: "dotted",
    style_dashed: "dashed",
    style_arrow_left: "arrow_left",
    style_arrow_right: "arrow_right",
    style_arrow_both: "arrow_both",
};

// ── label ───────────────────────────────────────────────────────────────────

export const label = {
    new: (
        ctx: Context, x: any, y: any, text: any = "",
        xloc: any = "bar_index", yloc: any = "price",
        color: any = "#2196F3", style: any = "label_down",
        textcolor: any = "#FFFFFF", size: any = "normal",
        textalign: any = "center", tooltip: any = "",
    ) => ctx.newDrawing("label", {
        x: n(x), y: n(y), text: String(v(text) ?? ""),
        xloc: v(xloc), yloc: v(yloc), color: v(color), style: v(style),
        textcolor: v(textcolor), size: v(size), textalign: v(textalign),
        tooltip: String(v(tooltip) ?? ""),
    }),

    set_x: (ctx: Context, id: any, x: any) => setNum(ctx, id, "label.set_x", "x", x),
    set_y: (ctx: Context, id: any, y: any) => setNum(ctx, id, "label.set_y", "y", y),
    set_text: (ctx: Context, id: any, text: any) => setProp(ctx, id, "label.set_text", "text", text),
    set_xloc: (ctx: Context, id: any, xloc: any) => setProp(ctx, id, "label.set_xloc", "xloc", xloc),
    set_yloc: (ctx: Context, id: any, yloc: any) => setProp(ctx, id, "label.set_yloc", "yloc", yloc),
    set_color: (ctx: Context, id: any, color: any) => setProp(ctx, id, "label.set_color", "color", color),
    set_style: (ctx: Context, id: any, style: any) => setProp(ctx, id, "label.set_style", "style", style),
    set_textcolor: (ctx: Context, id: any, textcolor: any) => setProp(ctx, id, "label.set_textcolor", "textcolor", textcolor),
    set_size: (ctx: Context, id: any, size: any) => setProp(ctx, id, "label.set_size", "size", size),
    set_textalign: (ctx: Context, id: any, textalign: any) => setProp(ctx, id, "label.set_textalign", "textalign", textalign),
    set_tooltip: (ctx: Context, id: any, tooltip: any) => setProp(ctx, id, "label.set_tooltip", "tooltip", tooltip),

    get_x: (ctx: Context, id: any) => getProp(ctx, id, "label.get_x", "x"),
    get_y: (ctx: Context, id: any) => getProp(ctx, id, "label.get_y", "y"),
    get_text: (ctx: Context, id: any) => getProp(ctx, id, "label.get_text", "text"),

    set_xy: (ctx: Context, id: any, x: any, y: any) => {
        const p = ctx.getDrawing(id, "label.set_xy").props;
        p.x = n(x); p.y = n(y);
    },

    delete: (ctx: Context, id: any) => {
        ctx.drawings.delete(String(v(id)));
    },
    copy: (ctx: Context, id: any) =>
        ctx.newDrawing("label", { ...ctx.getDrawing(id, "label.copy").props }),

    style_none: "none",
    style_xcross: "xcross",
    style_cross: "cross",
    style_triangleup: "triangleup",
    style_triangledown: "triangledown",
    style_flag: "flag",
    style_circle: "circle",
    style_arrowup: "arrowup",
    style_arrowdown: "arrowdown",
    style_label_up: "label_up",
    style_label_down: "label_down",
    style_label_left: "label_left",
    style_label_right: "label_right",
    style_label_lower_left: "label_lower_left",
    style_label_lower_right: "label_lower_right",
    style_label_upper_left: "label_upper_left",
    style_label_upper_right: "label_upper_right",
    style_label_center: "label_center",
    style_square: "square",
    style_diamond: "diamond",
};

// ── box ─────────────────────────────────────────────────────────────────────

export const box = {
    new: (
        ctx: Context, left: any, top: any, right: any, bottom: any,
        border_color: any = "#2196F3", border_width: any = 1,
        border_style: any = "solid", extend: any = "none", bgcolor: any = null,
    ) => ctx.newDrawing("box", {
        left: n(left), top: n(top), right: n(right), bottom: n(bottom),
        border_color: v(border_color), border_width: n(border_width),
        border_style: v(border_style), extend: v(extend), bgcolor: v(bgcolor),
    }),

    set_left: (ctx: Context, id: any, left: any) => setNum(ctx, id, "box.set_left", "left", left),
    set_top: (ctx: Context, id: any, top: any) => setNum(ctx, id, "box.set_top", "top", top),
    set_right: (ctx: Context, id: any, right: any) => setNum(ctx, id, "box.set_right", "right", right),
    set_bottom: (ctx: Context, id: any, bottom: any) => setNum(ctx, id, "box.set_bottom", "bottom", bottom),
    set_border_width: (ctx: Context, id: any, width: any) => setNum(ctx, id, "box.set_border_width", "border_width", width),
    set_border_color: (ctx: Context, id: any, color: any) => setProp(ctx, id, "box.set_border_color", "border_color", color),
    set_border_style: (ctx: Context, id: any, style: any) => setProp(ctx, id, "box.set_border_style", "border_style", style),
    set_extend: (ctx: Context, id: any, extend: any) => setProp(ctx, id, "box.set_extend", "extend", extend),
    set_bgcolor: (ctx: Context, id: any, bgcolor: any) => setProp(ctx, id, "box.set_bgcolor", "bgcolor", bgcolor),

    get_left: (ctx: Context, id: any) => getProp(ctx, id, "box.get_left", "left"),
    get_top: (ctx: Context, id: any) => getProp(ctx, id, "box.get_top", "top"),
    get_right: (ctx: Context, id: any) => getProp(ctx, id, "box.get_right", "right"),
    get_bottom: (ctx: Context, id: any) => getProp(ctx, id, "box.get_bottom", "bottom"),

    set_lefttop: (ctx: Context, id: any, left: any, top: any) => {
        const p = ctx.getDrawing(id, "box.set_lefttop").props;
        p.left = n(left); p.top = n(top);
    },
    set_rightbottom: (ctx: Context, id: any, right: any, bottom: any) => {
        const p = ctx.getDrawing(id, "box.set_rightbottom").props;
        p.right = n(right); p.bottom = n(bottom);
    },

    delete: (ctx: Context, id: any) => {
        ctx.drawings.delete(String(v(id)));
    },
    copy: (ctx: Context, id: any) =>
        ctx.newDrawing("box", { ...ctx.getDrawing(id, "box.copy").props }),

    style_solid: "solid",
    style_dotted: "dotted",
    style_dashed: "dashed",
};

// ── table ───────────────────────────────────────────────────────────────────

export const table = {
    new: (
        ctx: Context, position: any, columns: any, rows: any,
        bgcolor: any = null, frame_color: any = null, frame_width: any = 0,
        border_color: any = null, border_width: any = 0,
    ) => ctx.newDrawing("table", {
        position: v(position), columns: n(columns), rows: n(rows),
        bgcolor: v(bgcolor), frame_color: v(frame_color), frame_width: n(frame_width),
        border_color: v(border_color), border_width: n(border_width),
        // Cells are sparse — a table is usually mostly empty, and a dense
        // rows×columns allocation would be built on every bar.
        cells: new Map<string, Record<string, any>>(),
    }),

    cell: (
        ctx: Context, table_id: any, column: any, row: any, text: any = "",
        width: any = 0, height: any = 0, text_color: any = "#000000",
        text_halign: any = "center", text_valign: any = "center",
        text_size: any = "normal", bgcolor: any = null,
    ) => {
        const p = ctx.getDrawing(table_id, "table.cell").props;
        p.cells.set(`${n(column)},${n(row)}`, {
            text: String(v(text) ?? ""), width: n(width), height: n(height),
            text_color: v(text_color), text_halign: v(text_halign),
            text_valign: v(text_valign), text_size: v(text_size), bgcolor: v(bgcolor),
        });
    },

    set_cell_text: (ctx: Context, table_id: any, column: any, row: any, text: any) => {
        const p = ctx.getDrawing(table_id, "table.set_cell_text").props;
        const key = `${n(column)},${n(row)}`;
        const cell = p.cells.get(key) ?? {};
        cell.text = String(v(text) ?? "");
        p.cells.set(key, cell);
    },

    set_position: (ctx: Context, id: any, position: any) => {
        ctx.getDrawing(id, "table.set_position").props.position = v(position);
    },
    set_bgcolor: (ctx: Context, id: any, bgcolor: any) => {
        ctx.getDrawing(id, "table.set_bgcolor").props.bgcolor = v(bgcolor);
    },

    clear: (ctx: Context, id: any) => {
        ctx.getDrawing(id, "table.clear").props.cells.clear();
    },
    delete: (ctx: Context, id: any) => {
        ctx.drawings.delete(String(v(id)));
    },
};

// ── Shared placement constants ──────────────────────────────────────────────

/** `xloc` — whether an x coordinate is a bar index or a UNIX time. */
export const xloc = {
    bar_index: "bar_index",
    bar_time: "bar_time",
};

/** `yloc` — whether a y coordinate is a price or is pinned to the bar. */
export const yloc = {
    price: "price",
    abovebar: "abovebar",
    belowbar: "belowbar",
};

/** `extend` — how far a line or box runs past its endpoints. */
export const extend = {
    none: "none",
    right: "right",
    left: "left",
    both: "both",
};

/** `position` — where a table sits on the chart. */
export const position = {
    top_left: "top_left",
    top_center: "top_center",
    top_right: "top_right",
    middle_left: "middle_left",
    middle_center: "middle_center",
    middle_right: "middle_right",
    bottom_left: "bottom_left",
    bottom_center: "bottom_center",
    bottom_right: "bottom_right",
};

/** `text.align_*` — v4 spells these on the `text` namespace. */
export const text = {
    align_left: "left",
    align_center: "center",
    align_right: "right",
    align_top: "top",
    align_bottom: "bottom",
};
