import { Context as ContextV2 } from "../v2";
import { __SIGNATURES__, __CONTEXT_AWARE__ } from "../v2/stdlib";
import { Series } from "../v2/Series";

export class Context extends ContextV2 {
    
    // Registry for User-Defined Functions
    // Key: Function Name (e.g. "f"), Value: Param Names ["a", "b"]
    private userSignatures: Map<string, string[]> = new Map();

    /**
     * Called by the transpiled script to register a custom function.
     */
    public registerUserFunc(name: string, params: string[]) {
        this.userSignatures.set(name, params);
    }


    public call(id: string, fn: Function, ...args: any[]) {
        const identity = id; 
        this.callStack.push(identity);
        
        try {
            // 1. Extract Function Name from ID (e.g. "ta.sma_L10_C4" -> "ta.sma")
            // We strip the Location Tag (_Lxx_Cxx)
            const name = id.split("_L")[0]; 

            // 2. Handle Keyword Arguments
            // Check if the last argument is a Kwargs Object (generated by Transpiler)
            const lastArg = args[args.length - 1];
            const hasKwargs = lastArg && typeof lastArg === 'object' && !Array.isArray(lastArg) 
                                && !(lastArg instanceof Series) && lastArg.constructor === Object;

            let finalArgs = args;

            if (hasKwargs) {
                // Remove the kwargs object from the list
                const positionalArgs = args.slice(0, -1);
                const kwargs = lastArg;

                // Lookup Signature
                const params = __SIGNATURES__[name];
                
                if (params) {
                    finalArgs = [...positionalArgs];
                    
                    // Map keys (e.g. "color") to their index
                    for (const [key, val] of Object.entries(kwargs)) {
                        const index = params.indexOf(key);
                        if (index !== -1) {
                            // Pad array if needed
                            while (finalArgs.length < index) {
                                finalArgs.push(undefined);
                            }
                            finalArgs[index] = val;
                        }
                    }
                } else {
                    // Fallback: If no signature found (User function?), keep args as is
                    // or define behavior for user-defined kwargs (not supported in v2)
                    finalArgs = positionalArgs; 
                }
            }

            // 3. Inject Context (if required)
            if (__CONTEXT_AWARE__.includes(name)) {
                return fn(this, ...finalArgs);
            } else {
                return fn(...finalArgs);
            }

        } finally {
            this.callStack.pop();
        }
    }

}
